Enable live reloading in Docker Compose by combining Air and watch

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -26,15 +26,23 @@ services:
           cp elastic/elastic.crt -d ./http_ca.crt;
           # echo "Certificate copy successful"
         fi;
-        if ! [[ $(stat -c "%a" main) =~ "751" ]]; then
-          echo "Adding missing executable permissions to main";
-          chmod a+x main;
-          # echo "Executable permissions added to main";
-        fi;
         echo "Running make compose";
         # sleep infinity;
+        if [ ! -f .ait.toml ]; then
+          echo "Running air init";
+          air init;
+        fi;
+        if ! [[ $(stat -c "%a" tmp/main) =~ "755" ]]; then
+          echo "Adding missing executable permissions to main generated by Air";
+          chmod a+x tmp/main;
+        fi;
         make compose;
       '
+    develop:
+      watch:
+        - action: sync
+          path: ./
+          target: /usr/src/app
 
   pg:
     image: postgres:16
